name: five_stars_laundry
description: "Application for five stars laundromat."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.1
  http: ^1.3.0
  intl: ^0.20.1
  mailer: ^6.4.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.5 #5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/MyIcon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ecf0f1"
  adaptive_icon_foreground: "assets/icon/MyIcon.png"

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/FiveStarsLaundromat.png
    - assets/ImageOne.png
    - assets/ImageTwo.png
    - assets/CustomerManagementIcon.png
    - assets/EmployeeManagementIcon.png
  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf


